source("l1","x").
source("l2","y").

sink("l9","x").
sink("l10","y").
sink("l11","z").

follows("l2","l1").
follows("l3","l2").
follows("l4","l3").
follows("l5","l4").
follows("l6","l2").
follows("l7","l6").
follows("l8","l7").
follows("l9","l5").
follows("l9","l8").
follows("l10","l9").
follows("l11","l10").

join("l9","l5","l8").

assign("l4","z","x","0").
assign("l7","z","y","0").

if("l3","l4","x","y").
if("l6","l7","x","y").
