source("l1","x").

sink("l10","w").
sink("l11","y").


follows("l2","l1").
follows("l3","l2").
follows("l4","l3").
follows("l5","l4").
follows("l6","l1").
follows("l7","l6").
follows("l8","l7").
follows("l9","l8").
follows("l10","l5").
follows("l10","l9").
follows("l11","l10").

join("l10","l5","l9").

assign("l3","w","x","0").
assign("l4","y","x","0").
assign("l7","w","0","0").
assign("l8","y","0","0").

if("l2","l3","z","0").
if("l6","l7","z","0").
