source("l1","x").
source("l2","y").
source("l3","z").

sink("l20","w").

follows("l2","l1").
follows("l3","l2").
follows("l4","l3").
follows("l5","l4").
follows("l6","l5").
follows("l7","l6").
follows("l8","l4").
follows("l9","l8").
follows("l10","l9").
follows("l11","l7").
follows("l11","l10").
follows("l12","l3").
follows("l13","l12").
follows("l14","l13").
follows("l15","l14").
follows("l16","l12").
follows("l17","l16").
follows("l18","l17").
follows("l19","l15").
follows("l19","l18").
follows("l20","l11").
follows("l20","l19").

join("l11","l7","l10").
join("l19","l15","l18").
join("l20","l11","l19").

assign("l6","w","y","z").
assign("l9","w","0","0").
assign("l14","w","x","0").
assign("l17","w","1","0").


if("l4","l5","u","0").
if("l5","l6","v","0").
if("l8","l9","v","0").
if("l12","l13","u","0").
if("l13","l14","v","0").
if("l16","l17","v","0").
