source("l1","x").
source("l2","y").
source("l3","z").
source("l4","s").

sink("l15","u").
sink("l16","v").
sink("l17","w").

follows("l2","l1").
follows("l3","l2").
follows("l4","l3").
follows("l5","l4").
follows("l6","l5").
follows("l7","l6").
follows("l8","l7").
follows("l9","l8").
follows("l10","l4").
follows("l11","l10").
follows("l12","l11").
follows("l13","l12").
follows("l14","l13").
follows("l15","l9").
follows("l15","l14").
follows("l16","l15").
follows("l17","l16").


join("l15","l9","l4").

assign("l6","u","x","y").
assign("l7","v","0","0").
assign("l8","w","0","0").
assign("l11","u","0","0").
assign("l12","v","y","z").
assign("l13","w","z","s").


if("l5","l6","t","0").
if("l10","l11","t","0").
