source("l1","x").

sink("l18","x").

follows("l2","l1").
follows("l3","l2").
follows("l4","l3").
follows("l5","l4").
follows("l6","l2").
follows("l7","l6").
follows("l8","l7").
follows("l9","l5").
follows("l9","l8").
follows("l10","l1").
follows("l11","l10").
follows("l12","l11").
follows("l13","l12").
follows("l14","l10").
follows("l15","l14").
follows("l16","l15").
follows("l17","l13").
follows("l17","l16").
follows("l18","l9").
follows("l18","l17").

join("l9","l5","l8").
join("l17","l13","l16").
join("l18","l9","l17").

assign("l4","x","y","z").
assign("l7","u","0","0").
assign("l12","u","y","0").
assign("l15","u","z","0").


if("l2","l3","y","0").
if("l3","l4","z","0").
if("l6","l7","z","0").
if("l10","l11","y","0").
if("l11","l12","z","0").
if("l14","l15","z","0").
