.symbol_type Node

//
// Edge
//
.decl Edge(n:Node, m:Node)

Edge("n0","n1").
Edge("n1","n2").
Edge("n2","n3").
Edge("n1","n4").

//
// Reachable
//

.decl Reachable(n:Node, m:Node)
.output Reachable(IO=stdout)

// Relation Edge is a subset of relation Reachable
Reachable(x,y) :- Edge(x,y).

// Reflexive rules
Reachable(x,x) :- Edge(x,_).
Reachable(y,y) :- Edge(_,y).

// Transitive rule
Reachable(x,y) :- Edge(x,z), Reachable(z,y).
